# submarine — low-light red sub control room

background           #0a0000
foreground           #cc4444
cursor               #cc4444
cursor_text_color    #0a0000

selection_background #cc4444
selection_foreground #0a0000

url_color            #ffaa44

color0  #0a0000
color8  #400000
color1  #ff3333
color9  #ff6666
color2  #cc4444
color10 #ee6666
color3  #ffaa44
color11 #ffcc77
color4  #885566
color12 #aa6677
color5  #aa3344
color13 #cc4466
color6  #ff9988
color14 #ffbbaa
color7  #ffe6e6
color15 #ffffff

active_tab_foreground   #0a0000
active_tab_background   #cc4444
inactive_tab_foreground #400000
inactive_tab_background #0a0000
